export type {
	ExpiredPromptLifecycle,
	PromptEventAttribution,
	PromptLifecycleCancellationResult,
	PromptLifecycleEvent,
	PromptLifecycleKind,
	PromptLifecyclePhase,
	PromptLifecycleSnapshot,
	PromptLifecycleStateSnapshot,
} from "../../core/prompt-lifecycle.js";
export type {
	DaemonEventCursor,
	DaemonRecoverableOwnedSessionAdoptionProof,
	DaemonRecoverableOwnedSessionConfirmResult,
	DaemonRecoverableOwnedSessionCreateResult,
	DaemonRecoverableOwnedSessionPrepareResult,
} from "../daemon/daemon-protocol.js";
export type {
	DaemonAgentConnectionOptions,
	DaemonOwnedSessionContractProof,
	DaemonOwnedSessionDaemonIdentity,
	DaemonOwnedSessionDisposeOptions,
	DaemonOwnedSessionDisposeResult,
	DaemonRecoverableOwnedSessionAdoptionOptions,
	DaemonRecoverableOwnedSessionAdoptionResult,
} from "./daemon-agent-connection.js";
export { DaemonAgentConnection } from "./daemon-agent-connection.js";
export { InProcessAgentConnection } from "./in-process-agent-connection.js";
export {
	adoptRecoverableOwnedSession,
	confirmRecoverableOwnedSessionAdoption,
	createRecoverableOwnedSession,
	type RecoverableOwnedSessionAdoption,
	type RecoverableOwnedSessionAdoptionConfirmation,
	type RecoverableOwnedSessionAdoptionOptions,
	type RecoverableOwnedSessionCreateOptions,
	type RecoverableOwnedSessionCreation,
} from "./recoverable-owned-session.js";

export { createAgentConnectionCommands, createAgentConnectionState } from "./snapshot.js";
export type {
	AgentConnection,
	AgentConnectionAgentStatus,
	AgentConnectionArtifactReference,
	AgentConnectionArtifactType,
	AgentConnectionBeforeSessionInvalidateListener,
	AgentConnectionBranchSummaryEntry,
	AgentConnectionChildUsageAttributionEntry,
	AgentConnectionCompactionEntry,
	AgentConnectionCorrelatedPromptOptions,
	AgentConnectionCorrelatedPromptResult,
	AgentConnectionCustomEntry,
	AgentConnectionCustomMessageEntry,
	AgentConnectionEvent,
	AgentConnectionEventListener,
	AgentConnectionExtensionUiRequest,
	AgentConnectionExtensionUiResponse,
	AgentConnectionForkOptions,
	AgentConnectionHeartbeat,
	AgentConnectionLabelEntry,
	AgentConnectionModel,
	AgentConnectionModelCatalog,
	AgentConnectionModelChangeEntry,
	AgentConnectionModelCycleResult,
	AgentConnectionNavigateTreeOptions,
	AgentConnectionNavigateTreeResult,
	AgentConnectionNewSessionOptions,
	AgentConnectionParentMetadata,
	AgentConnectionPromptOptions,
	AgentConnectionQueuedMessageMutationStatus,
	AgentConnectionQueueMode,
	AgentConnectionQueueState,
	AgentConnectionReplayInfo,
	AgentConnectionReplayStatus,
	AgentConnectionResourceCollision,
	AgentConnectionResourceContextFile,
	AgentConnectionResourceDiagnostic,
	AgentConnectionResourceDiagnostics,
	AgentConnectionResourceExtension,
	AgentConnectionResourcePrompt,
	AgentConnectionResourceSkill,
	AgentConnectionResourceSnapshot,
	AgentConnectionResourceTheme,
	AgentConnectionRlmChildAgentActivity,
	AgentConnectionRlmChildAgentSnapshot,
	AgentConnectionRlmChildAgentStatus,
	AgentConnectionSavedSessionInfo,
	AgentConnectionSavedSessionScope,
	AgentConnectionSavedSessionState,
	AgentConnectionSavedSessionStateStatus,
	AgentConnectionScopedModel,
	AgentConnectionSessionContext,
	AgentConnectionSessionEntry,
	AgentConnectionSessionEntryBase,
	AgentConnectionSessionEvent,
	AgentConnectionSessionInfoEntry,
	AgentConnectionSessionListCallbacks,
	AgentConnectionSessionListProgress,
	AgentConnectionSessionMessageEntry,
	AgentConnectionSessionStateEntry,
	AgentConnectionSessionTreeNode,
	AgentConnectionSessionWatcher,
	AgentConnectionSideQuestionEvent,
	AgentConnectionSideQuestionTurn,
	AgentConnectionSlashCommand,
	AgentConnectionSnapshot,
	AgentConnectionSourceInfo,
	AgentConnectionSourceOrigin,
	AgentConnectionSourceScope,
	AgentConnectionState,
	AgentConnectionSwitchSessionOptions,
	AgentConnectionThinkingLevelChangeEntry,
	AgentConnectionToolDefinition,
	AgentConnectionUserMessage,
} from "./types.js";
export { AgentConnectionPromptAdmissionError } from "./types.js";
